// js/data.js

const STOKERO_IMG = ''; // mascot image removed for performance

const BGM_LIST = [
  { src: '', title: 'Golden Karaage Dream' },
  { src: '', title: 'Karaage no Story' },
  { src: '', title: 'ストケロ君の歌（関西版）' },
];


const MENU_ITEMS = [
  {id:1,  emoji:'🍡', name:'モダンストーリー焼き',        cat:'ストーリー焼き', group:'food', sub:'ストーリー焼き', price:500, tag:'⭐看板！',   desc:'外カリ中もちもち。STORYの看板メニュー。', to:true},
  {id:2,  emoji:'🍡', name:'もちもちストーリー焼き',      cat:'ストーリー焼き', group:'food', sub:'ストーリー焼き', price:500, tag:'',           desc:'やわらかもちもち食感が大人気。', to:true},
  {id:3,  emoji:'🍡', name:'豚ネギトロストーリー焼き',    cat:'ストーリー焼き', group:'food', sub:'ストーリー焼き', price:500, tag:'',           desc:'豚・ネギ・トロのバランスが絶妙。', to:true},
  {id:4,  emoji:'🍡', name:'豚玉トロストーリー焼き',      cat:'ストーリー焼き', group:'food', sub:'ストーリー焼き', price:500, tag:'',           desc:'豚と玉子のやさしい組み合わせ。', to:true},
  {id:5,  emoji:'🧄', name:'ガリバタからあげ定食',        cat:'定食', group:'food', sub:'定食', price:950, tag:'🧄人気No.1', desc:'超ニンニク香るガリバタソース！ご飯・サラダ・味噌汁付き。冷めても美味しい！', to:true},
  {id:6,  emoji:'🍗', name:'鶏チャーシュー定食',          cat:'定食', group:'food', sub:'定食', price:950, tag:'',           desc:'超肉厚の鶏チャーシューが主役。', to:true},
  {id:7,  emoji:'🍛', name:'チキンカツカレーうどん定食',  cat:'定食', group:'food', sub:'定食', price:850, tag:'',           desc:'カレーうどんとチキンカツの夢のコラボ。', to:true},
  {id:8,  emoji:'🍗', name:'ネギだれチキンカツ定食',      cat:'定食', group:'food', sub:'定食', price:850, tag:'',           desc:'さっぱりネギだれのチキンカツ定食。', to:true},
  {id:9,  emoji:'🍗', name:'からあげ定食（増量）',        cat:'定食', group:'food', sub:'定食', price:850, tag:'🔥ボリューム', desc:'ジューシーな唐揚げ山盛り！ご飯・味噌汁付き。', to:true},
  {id:10, emoji:'🍱', name:'コロッケ定食',                cat:'定食', group:'food', sub:'定食', price:850, tag:'',           desc:'ほくほくコロッケのやさしい定食。', to:true},
  {id:11, emoji:'🍱', name:'ミックスフライ定食',          cat:'定食', group:'food', sub:'定食', price:950, tag:'',           desc:'各種フライが楽しめるミックス定食。', to:true},
  {id:12, emoji:'🍜', name:'かす焼きそば（目玉焼き添え）',cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:450, tag:'',  desc:'旨みたっぷりかす焼きそば。', to:true},
  {id:13, emoji:'🍜', name:'イカ焼きそば（目玉焼き添え）',cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:450, tag:'',  desc:'イカのうまみが詰まった焼きそば。', to:true},
  {id:14, emoji:'🍜', name:'特濃カレーラーメン',          cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:450, tag:'🏠店内限定', desc:'コクのある特製カレーラーメン。伸びるため店内限定。', to:false},
  {id:15, emoji:'🍜', name:'豚ネギラーメン',              cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:450, tag:'🏠店内限定', desc:'豚とネギのシンプルうまラーメン。伸びるため店内限定。', to:false},
  {id:16, emoji:'🍚', name:'特製大盛エビチャーハン',      cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:450, tag:'',   desc:'プリプリエビ入り大盛チャーハン。', to:true},
  {id:17, emoji:'🍚', name:'とろとろあんかけ天津エビチャーハン', cat:'麺・ご飯', group:'food', sub:'麺・ご飯', price:600, tag:'', desc:'とろとろあんかけが絶品。', to:true},
  {id:18, emoji:'🍢', name:'冷え冷え奴豆腐',              cat:'おつまみ', group:'food', sub:'おつまみ', price:200, tag:'🏠店内推奨', desc:'ひんやり冷たい冷奴。', to:false},
  {id:19, emoji:'🍢', name:'絶品揚げ出し豆腐',            cat:'おつまみ', group:'food', sub:'おつまみ', price:350, tag:'⭐絶品', desc:'外カリッ中ふわの揚げ出し豆腐。', to:true},
  {id:20, emoji:'🌿', name:'ホットする大盛枝豆',          cat:'おつまみ', group:'food', sub:'おつまみ', price:350, tag:'',   desc:'ほっこり温かい大盛り枝豆。', to:true},
  {id:21, emoji:'🥔', name:'ほくほくコロッケ（2個）',     cat:'おつまみ', group:'food', sub:'おつまみ', price:300, tag:'',   desc:'ほくほく大きめコロッケ2個。', to:true},
  {id:22, emoji:'🥩', name:'定番ハムカツ（2個）',         cat:'おつまみ', group:'food', sub:'おつまみ', price:300, tag:'',   desc:'サクサク定番ハムカツ2個。', to:true},
  {id:23, emoji:'🥟', name:'大粒焼売（4個）',             cat:'おつまみ', group:'food', sub:'おつまみ', price:300, tag:'',   desc:'大粒でジューシーな焼売4個。', to:true},
  {id:24, emoji:'🥟', name:'大粒あげシュウマイ（6個）',   cat:'おつまみ', group:'food', sub:'おつまみ', price:400, tag:'',   desc:'揚げたてサクサクシュウマイ6個。', to:true},
  {id:25, emoji:'🍗', name:'でか唐揚げ（ふつう味）',      cat:'おつまみ', group:'food', sub:'おつまみ', price:300, tag:'🔥でか！', desc:'ガッツリでかい唐揚げ。', to:true},
  {id:26, emoji:'🧄', name:'でか唐揚げ（ニンニクマシマシ）', cat:'おつまみ', group:'food', sub:'おつまみ', price:400, tag:'🧄ニンニク', desc:'ニンニクたっぷりのでか唐揚げ。', to:true},
  {id:27, emoji:'🥗', name:'マカロニサラダ（ホット/アイス）', cat:'おつまみ', group:'food', sub:'おつまみ', price:350, tag:'', desc:'温冷どちらでも楽しめるマカロニサラダ。', to:true},
  {id:28, emoji:'🍿', name:'ポップコーン（5種の味）',     cat:'ライトフード', group:'light', sub:'ライトフード', price:100, tag:'💰激安', desc:'塩/カレー/のり塩/しょうゆ/キャラメル。', to:true},
  {id:29, emoji:'🍿', name:'特盛ポップコーン（大人ver）', cat:'ライトフード', group:'light', sub:'ライトフード', price:450, tag:'💚こども食堂', desc:'超デカ盛り！ご注文の一部がこども食堂へ。', to:true, kodomo:true},
  {id:30, emoji:'🍟', name:'皮付きポテト',                cat:'ライトフード', group:'light', sub:'ライトフード', price:200, tag:'', desc:'カリカリ皮付きフライドポテト。', to:true},
  {id:31, emoji:'🍩', name:'チュロス（3種の味）',         cat:'ライトフード', group:'light', sub:'ライトフード', price:200, tag:'', desc:'プレーン/シナモン/ココア。', to:true},
  {id:32, emoji:'🍩', name:'大人なチュロス爆盛り',        cat:'ライトフード', group:'light', sub:'ライトフード', price:500, tag:'💚こども食堂', desc:'爆盛りチュロス約3個分！こども食堂支援。', to:true, kodomo:true},
  {id:33, emoji:'🍕', name:'キャラメルアイスピザ',        cat:'ライトフード', group:'light', sub:'ライトフード', price:300, tag:'', desc:'甘いキャラメルとバニラアイスのピザ。', to:true},
  {id:34, emoji:'🍓', name:'ストロベリーキャラメルアイスピザ', cat:'ライトフード', group:'light', sub:'ライトフード', price:400, tag:'', desc:'いちご×キャラメルのデザートピザ。', to:true},
  {id:35, emoji:'🧋', name:'定番タピオカミルクティー',    cat:'タピオカ', group:'drink', sub:'タピオカ', price:350, tag:'',   desc:'もちもちタピオカたっぷり。定番の一杯。', to:true},
  {id:36, emoji:'🧋', name:'生クリームタピオカミルクティー', cat:'タピオカ', group:'drink', sub:'タピオカ', price:450, tag:'💚こども食堂', desc:'生クリームのせで贅沢！こども食堂支援。', to:true, kodomo:true},
  {id:37, emoji:'🍵', name:'濃い抹茶タピオカ',            cat:'タピオカ', group:'drink', sub:'タピオカ', price:450, tag:'',   desc:'濃厚な抹茶にもちもちタピオカ。', to:true},
  {id:38, emoji:'🍵', name:'生クリーム濃い抹茶タピオカ',  cat:'タピオカ', group:'drink', sub:'タピオカ', price:500, tag:'💚こども食堂', desc:'抹茶に生クリームで贅沢な一杯。こども食堂支援。', to:true, kodomo:true},
  {id:39, emoji:'🍓', name:'イチゴミルクタピオカ',        cat:'タピオカ', group:'drink', sub:'タピオカ', price:450, tag:'',   desc:'甘酸っぱいいちごミルクにタピオカ。', to:true},
  {id:40, emoji:'🍓', name:'生クリームイチゴタピオカ',    cat:'タピオカ', group:'drink', sub:'タピオカ', price:500, tag:'💚こども食堂', desc:'いちごミルクに生クリームたっぷり。こども食堂支援。', to:true, kodomo:true},
  {id:41, emoji:'🍋', name:'レモネード',                  cat:'ドリンク', group:'drink', sub:'ドリンク', price:250, tag:'',   desc:'さっぱり爽やかレモネード。', to:true},
  {id:42, emoji:'🍋', name:'濃い目のレモネード',          cat:'ドリンク', group:'drink', sub:'ドリンク', price:300, tag:'💚こども食堂', desc:'酸っぱさ強めの本格レモネード。こども食堂支援。', to:true, kodomo:true},
  {id:43, emoji:'🍓', name:'ストロベリーエード（クラッシュアイス）', cat:'ドリンク', group:'drink', sub:'ドリンク', price:450, tag:'', desc:'いちごの甘酸っぱさがクラッシュアイスで爽やか。', to:true},
  {id:44, emoji:'🟢', name:'クラッシュアイスフロート（5種）', cat:'ドリンク', group:'drink', sub:'ドリンク', price:300, tag:'', desc:'オレンジ/メロン/マスカット/コーラ/ブルーハワイ。', to:true},
  {id:45, emoji:'🍧', name:'贅沢かき氷（4種）',           cat:'ドリンク', group:'drink', sub:'ドリンク', price:450, tag:'🏠夏・店内専用', desc:'イチゴ/レモン/コーヒー/抹茶小豆。夏の来店時の楽しみ！', to:false},
  {id:46, emoji:'☕', name:'ホットコーヒー',              cat:'ホットドリンク', group:'drink', sub:'ホットドリンク', price:250, tag:'', desc:'ほっとするホットコーヒー。', to:true},
  {id:47, emoji:'🍵', name:'ホット紅茶',                  cat:'ホットドリンク', group:'drink', sub:'ホットドリンク', price:250, tag:'', desc:'温かい紅茶でひと息。', to:true},
  {id:48, emoji:'☕', name:'ホットキャラメルマキアート',  cat:'ホットドリンク', group:'drink', sub:'ホットドリンク', price:350, tag:'', desc:'キャラメリーゼなホットマキアート。', to:true},
  {id:49, emoji:'🍵', name:'ホット濃い宇治抹茶ミルク',    cat:'ホットドリンク', group:'drink', sub:'ホットドリンク', price:350, tag:'', desc:'濃い目の宇治抹茶ミルク。', to:true},
  {id:50, emoji:'🍓', name:'ホットイチゴミルク',          cat:'ホットドリンク', group:'drink', sub:'ホットドリンク', price:350, tag:'', desc:'温かいいちごミルク。', to:true},
  {id:51, emoji:'🍺', name:'生ビール（2種）',             cat:'お酒', group:'alcohol', sub:'お酒', price:500, tag:'', desc:'サッポロ / アサヒスーパードライ。', to:true},
  {id:52, emoji:'🍺', name:'発泡酒（ジョッキ生）',        cat:'お酒', group:'alcohol', sub:'お酒', price:450, tag:'', desc:'スッキリ飲める発泡酒ジョッキ。', to:true},
  {id:53, emoji:'🥃', name:'キンミヤ焼酎（3種の割り方）', cat:'お酒', group:'alcohol', sub:'お酒', price:450, tag:'', desc:'ロック/ハイボール/紅茶割り。', to:true},
  {id:54, emoji:'🥃', name:'レモンサワー',                cat:'お酒', group:'alcohol', sub:'お酒', price:450, tag:'', desc:'定番さっぱりレモンサワー。', to:true},
  {id:55, emoji:'🥃', name:'クラッシュアイスレモンサワー', cat:'お酒', group:'alcohol', sub:'お酒', price:500, tag:'', desc:'氷たっぷりクラッシュアイスのレモンサワー。', to:true},
  {id:56, emoji:'🍷', name:'サングリア（ホット/クラッシュアイス）', cat:'お酒', group:'alcohol', sub:'お酒', price:500, tag:'', desc:'果実風味のサングリア。温冷どちらでも。', to:true},
  {id:57, emoji:'🍹', name:'食べられるカクテル・マリブマンゴー', cat:'カクテル', group:'alcohol', sub:'カクテル', price:600, tag:'🍹果肉入り', desc:'マンゴー果肉たっぷりマリブカクテル。', to:true},
  {id:58, emoji:'🍹', name:'食べられるカクテル・カシスレモン', cat:'カクテル', group:'alcohol', sub:'カクテル', price:600, tag:'🍹果肉入り', desc:'カシスレモンの果肉入りカクテル。', to:true},
  {id:59, emoji:'🍸', name:'ジントニック',                cat:'カクテル', group:'alcohol', sub:'カクテル', price:500, tag:'', desc:'爽やかなジントニック。', to:true},
  {id:60, emoji:'🍸', name:'モスコミュール',              cat:'カクテル', group:'alcohol', sub:'カクテル', price:500, tag:'', desc:'ジンジャービア×ウォッカのモスコミュール。', to:true},
  {id:61, emoji:'🍸', name:'カルーアミルク',              cat:'カクテル', group:'alcohol', sub:'カクテル', price:500, tag:'', desc:'まろやかなカルーアミルク。', to:true},
  {id:62, emoji:'🍸', name:'マリブアップル/コーク/ミルク', cat:'カクテル', group:'alcohol', sub:'カクテル', price:500, tag:'', desc:'選べる3種のマリブカクテル。', to:true},
];

const GROUP_DEF = {
  all:     { label:'すべて',       subs:[] },
  food:    { label:'フード',        subs:[{key:'定食',label:'🍱 定食'},{key:'ストーリー焼き',label:'🍡 ストーリー焼き'},{key:'麺・ご飯',label:'🍜 麺・ご飯'},{key:'おつまみ',label:'🍢 おつまみ'}] },
  light:   { label:'軽食・スイーツ', subs:[{key:'ライトフード',label:'🍟 軽食・スイーツ'}] },
  drink:   { label:'ドリンク',       subs:[{key:'タピオカ',label:'🧋 タピオカ'},{key:'ドリンク',label:'🥤 ドリンク'},{key:'ホットドリンク',label:'☕ ホット'}] },
  alcohol: { label:'お酒・カクテル', subs:[{key:'お酒',label:'🍺 お酒'},{key:'カクテル',label:'🍹 カクテル'}] },
  kodomo:  { label:'💚 こども食堂',   subs:[] },
};

const DEFAULT_REVIEWS = [
  {stars:5, text:'ストーリー焼きが本当においしい！外がカリッとして中はもちもち。他の店では食べられないメニューです。', nick:'ゆうこ', date:'2025-03'},
  {stars:5, text:'ガリバタからあげ定食がボリューム満点でコスパ最高！またリピートします。', nick:'ファン', date:'2025-02'},
  {stars:5, text:'タピオカも種類が多くて迷いました。生クリームのやつが最高においしかった💚', nick:'まみ', date:'2025-03'},
  {stars:5, text:'こども食堂支援をやっているお店と聞いて来ました。食事もおいしくてまた来ます！', nick:'地域の方', date:'2025-01'},
];

const GALLERY_EMOJIS = ['🧄','🍡','🧋','🍗','🍩','🍹','🍿','🍟','🍺','🍓','🥃','☕','🍜','🥗','🍢'];

const NEWS_LIST = [
  {
    id: 'paypay-2025-03',
    file: 'paypay-2025-03.html',
    date: '2025.03',
    badge: 'NEW',
    badgeClass: 'new',
    title: 'PayPay対応を開始しました',
    summary: '現金・PayPay両方ご利用いただけます。QRコードをスキャンするだけでスムーズにお支払いいただけます🎉',
  },
  {
    id: 'banquet-2025-03',
    file: 'banquet-2025-03.html',
    date: '2025.03',
    badge: '宴会',
    badgeClass: 'event',
    title: '宴会コースプラン3種を新設しました',
    summary: 'ゲームプラン・ガッツリプラン・フルプランの3種。川口市内でボードゲームが楽しめる唯一のお店！',
  },
  {
    id: 'renewal-2025-03',
    file: 'renewal-2025-03.html',
    date: '2025.03',
    badge: 'HP',
    badgeClass: '',
    title: 'ホームページをリニューアルしました',
    summary: 'テイクアウト注文・席予約・スタンプカード・クーポンがウェブから使えるようになりました。',
  },
  {
    id: 'uber-eats-2025',
    file: 'uber-eats-2025.html',
    date: '2025年春',
    badge: '近日',
    badgeClass: 'event',
    title: 'Uber Eats出店準備中！',
    summary: 'エリア内配達が近日スタート予定。開始後はInstagram（@story.kizoro）でお知らせします。',
  },
  {
    id: 'kodomo-shien',
    file: 'kodomo-shien.html',
    date: '2021〜継続中',
    badge: '支援',
    badgeClass: 'kodomo',
    title: 'こども食堂支援を継続しています',
    summary: '2021年より地域のこども食堂支援を継続中。みなさまのご注文の一部が地域の子どもたちへ届きます💚',
  },
];
